FROM ubuntu:14.04

ADD ./artifacts/mnist_inference.tar.gz /
ADD ./artifacts/mnist_model.tar.gz /

ENTRYPOINT [ "/src/serving/bazel-bin/tensorflow_serving/example/mnist_inference" ]
CMD [ "--port=9000", "/models/00000001/" ]
